spring:
  config:
      import:
        - optional:file:.env[.properties]
  application:
    name: Project

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:3600000}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:604800000}

openai:
  api:
    key: ${OPENAI_API_KEY}
    model: ${OPENAI_MODEL}
    url: https://api.openai.com/v1/chat/completions

sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: ${GOOGLE_CLIENT_ID:google-id}
      secret: ${GOOGLE_CLIENT_SECRET:google-secret}
    callback:
      url: http://localhost:8080/auth/google/callback # [수정] 순환참조 제거
    token:
      url: https://oauth2.googleapis.com/token
    userinfo:
      url: https://www.googleapis.com/oauth2/v2/userinfo
  kakao:
    url: https://kauth.kakao.com/oauth/authorize
    client:
      id: ${KAKAO_CLIENT_ID:kakao-id}
    callback:
      url: http://localhost:8080/auth/kakao/callback # [수정] 순환참조 제거
    token:
      url: https://kauth.kakao.com/oauth/token
    userinfo:
      url: https://kapi.kakao.com/v2/user/me
  naver:
    url: https://nid.naver.com/oauth2.0/authorize
    client:
      id: ${NAVER_CLIENT_ID:naver-id}
      secret: ${NAVER_CLIENT_SECRET:naver-secret}
    callback:
      url: http://localhost:8080/auth/naver/callback # [수정] 순환참조 제거
    token:
      url: https://nid.naver.com/oauth2.0/token
    userinfo:
      url: https://openapi.naver.com/v1/nid/me

springdoc:
  swagger-ui:
    path: /swagger-ui.html